# Builds a final release version and pushes to nuget.org 
# whenever a release is published.
# Requires: secrets.NUGET_API_KEY

name: publish
on:
  release:
    types: [released]

env:
  DOTNET_NOLOGO: true
  Configuration: Release

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: 🤘 checkout
        uses: actions/checkout@v2
        with: 
          submodules: recursive
          fetch-depth: 0
          
      - name: 🔍 msbuild
        uses: microsoft/setup-msbuild@v1
        with:
          vs-version: '[16.8,)'

      - name: \# version
        run: echo "VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
        shell: bash

      - name: 🙏 build
        run: msbuild -r -m:1 -bl:build.binlog 

      - name: 🧪 test
        run: |
          dotnet restore src\NuGetizer.Tests\Scenarios\given_a_packaging_project\a.nuproj
          msbuild -t:test

      - name: 📦 pack
        run: dotnet pack -m:1 --no-build -bl:pack.binlog

      - name: 🔼 logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          path: '**/*.binlog'

      - name: 🚀 nuget
        shell: bash
        run: dotnet nuget push bin\**\*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}} --skip-duplicate
